version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki.yaml
    networks:
      - observability

volumes:
  grafana-storage:

networks:
  observability:
