services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/app/config
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  datadir:
