version: "3"

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - /volume1/docker/tdsproxy/config:/config
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  datadir: