version: "3.8"

services:
  op-connect:
    image: 1password/connect-api:latest
    container_name: op-connect
    ports:
      - "8080:8080"
    environment:
      OP_BUS_PORT: 8080
    volumes:
      - ./secrets.json:/home/opuser/.op/connect-secrets.json:ro
    restart: unless-stopped

  op-sync:
    image: 1password/connect-sync:latest
    container_name: op-sync
    depends_on:
      - op-connect
    volumes:
      - ./secrets.json:/home/opuser/.op/connect-secrets.json:ro
    restart: unless-stopped
